name: Github Actions Test

on:
  push:
    branches:
      - 'brandon-changes'
env:
  WEBMASTER_GITHUB_ACTIONS_TOKEN: ${{ secrets.WEBMASTER_GITHUB_ACTIONS_TOKEN }}
jobs:
  # job1:
  #   name: Lint JavaScript
  #   runs-on: macos-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #     - run: npm install --save-dev

  #     - name: Run ESLint
  #       run: |
  #         npm run stylelint-report
  #         npm run eslint

  # job2:
  #   name: Lint PHP
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Set Up PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: 7.4
  #         tools: phpcbf

  #     - name: Install composer
  #       uses: ramsey/composer-install@v2

  #     - name: Run PHPCBF
  #       run: |
  #         composer update
  #         composer run-script phpcbf-prod

  job1:
    name: Assets
    # needs: [job1, job2]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Assets
        run: docker-compose --file storybook-build-compose.yml --project-directory . --verbose run builder
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  job2:
    name: Build Storybook
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Storybook
        uses: actions/download-artifact@v2
        with:
          name: dist
      - run: docker-compose --file storybook-build-compose.yml --project-directory . run storybook
