name: Github Actions Test

on:
  push:
    branches:
      - 'news-2.0'

  workflow_dispatch:

jobs:
  run-linters:
    name: Run Linters
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
      - run: npm install --save-dev

      - name: Run ESLint
        run: |
          npm run stylelint-report
          npm run eslint

      - name: Install Composer
        container: composer:2.0
        run: phpcbf-prod
